### ISSUE TITLE
lastest snapshot broken

### ISSUE THREAD

**Issue by maxisacoder** [bnb-chain/bsc-snapshots#76]
```
./geth_linux --config ./config.toml --datadir ./server/data-seed/ --diffsync --cache 12000 --rpc.allow-unprotected-txs --txlookuplimit 0 --usb
INFO [12-03|14:25:22.605] Starting Geth on Ethereum mainnet...
INFO [12-03|14:25:22.608] Maximum peer count                       ETH=100 LES=0 total=100
INFO [12-03|14:25:22.608] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [12-03|14:25:22.608] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x783533]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/rawdb.NewDatabaseWithFreezer(0x1b42fd8, 0xc00054e900, 0xc01008c7c0, 0x34, 0x16c1cd1, 0x11, 0x525900, 0xc00054e900, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/core/rawdb/database.go:198 +0x413
github.com/ethereum/go-ethereum/core/rawdb.NewLevelDBDatabaseWithFreezer(0xc000fe1d10, 0x2c, 0x1031, 0x80000, 0xc01008c7c0, 0x34, 0x16c1cd1, 0x11, 0xc0005bd200, 0x687d70, ...)
	github.com/ethereum/go-ethereum/core/rawdb/database.go:264 +0xf4
github.com/ethereum/go-ethereum/node.(*Node).OpenDatabaseWithFreezer(0xc000ffc4e0, 0x16b7748, 0x9, 0x1031, 0x80000, 0x0, 0x0, 0x16c1cd1, 0x11, 0x105c700, ...)
	github.com/ethereum/go-ethereum/node/node.go:628 +0x33c
github.com/ethereum/go-ethereum/node.(*Node).OpenAndMergeDatabase(0xc000ffc4e0, 0x16b7748, 0x9, 0x1031, 0x80000, 0x0, 0x0, 0x0, 0x0, 0x16c1cd1, ...)
	github.com/ethereum/go-ethereum/node/node.go:589 +0xee
github.com/ethereum/go-ethereum/eth.New(0xc000ffc4e0, 0xc000ec7500, 0xc000eff4b0, 0xc0005beab8, 0xfb4590)
	github.com/ethereum/go-ethereum/eth/backend.go:132 +0x336
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0xc000ffc4e0, 0xc000ec7500, 0xf, 0x0, 0x1)
	github.com/ethereum/go-ethereum/cmd/utils/flags.go:1811 +0x225
main.makeFullNode(0xc00003eb00, 0x16b4c63, 0x1, 0xc00011b860)
	github.com/ethereum/go-ethereum/cmd/geth/config.go:147 +0x125
main.geth(0xc00003eb00, 0x0, 0x0)
	github.com/ethereum/go-ethereum/cmd/geth/main.go:327 +0xf4
gopkg.in/urfave/cli%2ev1.HandleAction(0x14696a0, 0x19a3878, 0xc00003eb00, 0xc000320540, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc000d0a680, 0xc00003c0c0, 0xc, 0xc, 0x0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:267 +0x55
```

**Comment by a04512** [comment]
good for me geth-20211202.tar.gz

**Comment by nilampatel-engineer** [comment]
is geth-2021120.tar.gz still breaking?
